logging:
    level:
        root: ${federate.log.level:INFO}
        org.springframework: ERROR
region: ${federate.region}
env: ${federate.env}
issuer: ${federate.org}
keystore:
    path: ${federate.keystore.path}
    storePwd: ${federate.store.password}
    keyPwd: ${federate.key.password}
    awsProp: ${federate.aws.prop}
roles:
    dev:
        roleArn: ${federate.env}.dev.rolearn
        accountId: ${federate.env}.dev.accountid
        token: ${federate.env}.dev.token
        appClientId: ${federate.env}.dev.appclientid
        userPoolId: ${federate.env}.dev.userpoolid
        identityPoolId: ${federate.env}.dev.identitypoolid
    admin:
        roleArn: ${federate.env}.admin.rolearn
        accountId: ${federate.env}.admin.accountid
        token: ${federate.env}.admin.token
        appClientId: ${federate.env}.admin.appclientid
        userPoolId: ${federate.env}.admin.userpoolid
        identityPoolId: ${federate.env}.admin.identitypoolid


