#!/usr/bin/env bash

FEDERATE_LOG_LEVEL=INFO
FEDERATE_REGION=us-east-1
FEDERATE_ENV=prod2
FEDERATE_ORG=cmdfw
FEDERATE_JKS_PATH="${CMDFW_JKS_PATH}"
FEDERATE_STORE_PWD="${CMDFW_SP}"
FEDERATE_KEY_PWD="${CMDFW_KP}"
FEDERATE_AWS_PROP="${CMDFW_AWS_PROP}"

